### PR TITLE
Improve reliability

### PR DESCRIPTION
**Pull request by lorenzph**
While playing around with a project which publishes data in short intervals the device sporadically stopped publishing data right after a keep alive message was scheduled to be sent. This turned out to be issue #67.

Patch 1 of this patch set fixes the actual problem (there was not enough buffer space to queue the keep alive message while another send was still in progress). Patch 2 fixes the recovery code path to ensure that the connection is reestablished after an error is detected (I have not run into this case after applying patch 1 but this should increase robustness in case sending fails for another reason).

### CODE REVIEW

**Comment by lorenzph** [comment]
Some changes got lost while refactoring - second patch set fixes those.

**Comment by someburner** [comment]
Thanks for this. I was having the same issue for disconnect/reconnect. As for queuing, I have MQTT forwarding messages from another interface which has its own separate message queue. So I thought it was a bug on my end. My interim solution was to have my separate queue keep track of what had been published and calculate the buffer size, and simply not pub if the published() callback had not been triggered for a certain number of previous messages.

This seemed to work pretty well, but given what you've said here, I suppose I would still run into trouble eventually if there's not enough room for the keepalive message. Since you've delved into this more than I have, do you know how much buffer space the keepalive message requires or if that space get cleared on a timeout?

**Comment by lorenzph** [comment]
There seems to be a 2920 byte write buffer (or a maximum of 8 packets) if the ESPCONN_COPY option is enabled on the connection via espconn_set_opt(). I don't know if the IP header or TCP header account towards buffer usage or whether those are generated before transmission. In any case you're probably more likely to hit the 8 packet limit as the total keep alive message size (including IP & TCP header w/o options) is going to be around 42 bytes.

In any case espconn_send should only be called after the previous send has been acknowledged via the sent callback or if ESPCONN_COPY is set after espconn_regist_write_finish has been called.

I don't believe that the application level timeout implemented in esp_mqtt will actually clear the send buffer (in the end the TCP stack will still try to deliver the message or abort the connection if it fails to do so). The documentation states that espconn_reconnect_callback will be called on any kind of connection error so the application level timeout should probably also result in an early reconnect.

**Comment by tuanpmt** [comment]
:+1: Thanks

**Pull request merged**
